export type SocialKind = "instagram" | "facebook" | "threads" | "tiktok" | "linkedin" | "website";
export type MemberRole = "belle" | "beau" | "officer";
export type SocialLink = { kind: SocialKind; handle: string };
export type CallingCard = { id: string; name: string; role: MemberRole; office?: string; seasonJoined?: string; line: string; houseLine?: string; socials: SocialLink[] };
export const socialLabels: Record<SocialKind, string> = { instagram: "Instagram", facebook: "Facebook", threads: "Threads", tiktok: "TikTok", linkedin: "LinkedIn", website: "Website" };
export function roleLabel(role: MemberRole) { if (role === "beau") return "Les Beaux"; if (role === "officer") return "Officer"; return "Belle"; }
export function monogram(name: string) { const parts = name.trim().split(/\s+/).filter(Boolean); if (!parts.length) return "LB"; if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase(); return `${parts[0][0]}${parts[parts.length - 1][0]}`.toUpperCase(); }
function stripAt(handle: string) { return handle.trim().replace(/^@/, ""); }
export function socialUrl(link: SocialLink) { const raw = stripAt(link.handle); if (!raw) return ""; if (/^https?:\/\//i.test(raw)) return raw; if (link.kind === "instagram") return `https://instagram.com/${raw}`; if (link.kind === "facebook") return `https://facebook.com/${raw}`; if (link.kind === "threads") return `https://www.threads.net/@${raw}`; if (link.kind === "tiktok") return `https://www.tiktok.com/@${raw}`; if (link.kind === "linkedin") return `https://www.linkedin.com/in/${raw}`; if (raw.includes(".")) return `https://${raw}`; return ""; }
export function socialDisplay(link: SocialLink) { const raw = stripAt(link.handle); if (/^https?:\/\//i.test(raw)) { try { return new URL(raw).hostname.replace(/^www\./, ""); } catch { return raw; } } return raw.startsWith("@") ? raw : `@${raw}`; }
export const company: CallingCard[] = [];
const CARD_QUERY = "card";
function toBase64Url(value: string) { const bytes = new TextEncoder().encode(value); let binary = ""; bytes.forEach((byte) => { binary += String.fromCharCode(byte); }); return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, ""); }
function fromBase64Url(value: string) { const padded = value.replace(/-/g, "+").replace(/_/g, "/"); const pad = padded.length % 4 === 0 ? "" : "=".repeat(4 - (padded.length % 4)); const binary = atob(padded + pad); const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0)); return new TextDecoder().decode(bytes); }
function slimCard(card: CallingCard): CallingCard { return { id: card.id || `shared-${Date.now()}`, name: card.name.trim().slice(0, 80), role: card.role, office: card.office?.trim().slice(0, 60) || undefined, seasonJoined: card.seasonJoined?.trim().slice(0, 24) || undefined, line: card.line.trim().slice(0, 180), houseLine: card.houseLine?.trim().slice(0, 80) || undefined, socials: card.socials.filter((item) => item.handle.trim()).slice(0, 6).map((item) => ({ kind: item.kind, handle: item.handle.trim().slice(0, 80) })) }; }
export function encodeCard(card: CallingCard) { return toBase64Url(JSON.stringify(slimCard(card))); }
export function decodeCard(payload: string): CallingCard | null { try { const parsed = JSON.parse(fromBase64Url(payload)) as CallingCard; if (!parsed || typeof parsed.name !== "string" || !parsed.name.trim() || !parsed.line || typeof parsed.line !== "string") return null; const role: MemberRole = parsed.role === "beau" || parsed.role === "officer" ? parsed.role : "belle"; return slimCard({ id: typeof parsed.id === "string" ? parsed.id : `shared-${Date.now()}`, name: parsed.name, role, office: parsed.office, seasonJoined: parsed.seasonJoined, line: parsed.line, houseLine: parsed.houseLine, socials: Array.isArray(parsed.socials) ? parsed.socials : [] }); } catch { return null; } }
export function cardSharePath(card: CallingCard) { return `/company?${CARD_QUERY}=${encodeCard(card)}`; }
export function readSharedCard(search: string) { const params = new URLSearchParams(search.startsWith("?") ? search.slice(1) : search); const payload = params.get(CARD_QUERY); if (!payload) return null; return decodeCard(payload); }
export const emptyCard = (): CallingCard => ({ id: "mine", name: "", role: "belle", office: "", seasonJoined: "", line: "", houseLine: "", socials: [{ kind: "instagram", handle: "" }, { kind: "facebook", handle: "" }] });
