/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GivingRouteImport } from './routes/giving'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SisterhoodRouteImport } from './routes/sisterhood'
import { Route as SoireeRouteImport } from './routes/soiree'
import { Route as StageDoorRouteImport } from './routes/stage-door'
import { Route as StoryRouteImport } from './routes/story'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GivingRoute = GivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SisterhoodRoute = SisterhoodRouteImport.update({
  id: '/sisterhood',
  path: '/sisterhood',
  getParentRoute: () => rootRouteImport,
} as any)
const SoireeRoute = SoireeRouteImport.update({
  id: '/soiree',
  path: '/soiree',
  getParentRoute: () => rootRouteImport,
} as any)
const StageDoorRoute = StageDoorRouteImport.update({
  id: '/stage-door',
  path: '/stage-door',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/giving': typeof GivingRoute
  '/membership': typeof MembershipRoute
  '/shop': typeof ShopRoute
  '/sisterhood': typeof SisterhoodRoute
  '/soiree': typeof SoireeRoute
  '/stage-door': typeof StageDoorRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/giving': typeof GivingRoute
  '/membership': typeof MembershipRoute
  '/shop': typeof ShopRoute
  '/sisterhood': typeof SisterhoodRoute
  '/soiree': typeof SoireeRoute
  '/stage-door': typeof StageDoorRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/giving': typeof GivingRoute
  '/membership': typeof MembershipRoute
  '/shop': typeof ShopRoute
  '/sisterhood': typeof SisterhoodRoute
  '/soiree': typeof SoireeRoute
  '/stage-door': typeof StageDoorRoute
  '/story': typeof StoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/giving'
    | '/membership'
    | '/shop'
    | '/sisterhood'
    | '/soiree'
    | '/stage-door'
    | '/story'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/giving'
    | '/membership'
    | '/shop'
    | '/sisterhood'
    | '/soiree'
    | '/stage-door'
    | '/story'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/giving'
    | '/membership'
    | '/shop'
    | '/sisterhood'
    | '/soiree'
    | '/stage-door'
    | '/story'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  GivingRoute: typeof GivingRoute
  MembershipRoute: typeof MembershipRoute
  ShopRoute: typeof ShopRoute
  SisterhoodRoute: typeof SisterhoodRoute
  SoireeRoute: typeof SoireeRoute
  StageDoorRoute: typeof StageDoorRoute
  StoryRoute: typeof StoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giving': {
      id: '/giving'
      path: '/giving'
      fullPath: '/giving'
      preLoaderRoute: typeof GivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sisterhood': {
      id: '/sisterhood'
      path: '/sisterhood'
      fullPath: '/sisterhood'
      preLoaderRoute: typeof SisterhoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soiree': {
      id: '/soiree'
      path: '/soiree'
      fullPath: '/soiree'
      preLoaderRoute: typeof SoireeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage-door': {
      id: '/stage-door'
      path: '/stage-door'
      fullPath: '/stage-door'
      preLoaderRoute: typeof StageDoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  GivingRoute: GivingRoute,
  MembershipRoute: MembershipRoute,
  ShopRoute: ShopRoute,
  SisterhoodRoute: SisterhoodRoute,
  SoireeRoute: SoireeRoute,
  StageDoorRoute: StageDoorRoute,
  StoryRoute: StoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
